default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: P@ssw0rd
  host: localhost

development:
  <<: *default
  database: db_lms_dev

test:
  <<: *default
  database: db_lms_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  adapter: postgresql
  database: db_lms_production
  username: db_lms_user
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
